using CabriThonAPI.Application.Interfaces;
using Google.Cloud.AIPlatform.V1;
using Google.Protobuf.WellKnownTypes;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace CabriThonAPI.Infrastructure.Services;

public class GeminiAIService : IGeminiAIService
{
    private readonly ILogger<GeminiAIService> _logger;
    private readonly IConfiguration _configuration;
    private readonly string _projectId;
    private readonly string _location;
    private readonly string _modelId;

    public GeminiAIService(
        ILogger<GeminiAIService> logger,
        IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
        _projectId = _configuration["GeminiAI:ProjectId"] ?? "your-project-id";
        _location = _configuration["GeminiAI:Location"] ?? "us-central1";
        _modelId = _configuration["GeminiAI:ModelId"] ?? "gemini-1.5-flash";
    }

    public async Task<string> GeneratePromotionSuggestionAsync(string prompt)
    {
        try
        {
            var predictionServiceClient = await PredictionServiceClient.CreateAsync();
            
            var endpoint = $"projects/{_projectId}/locations/{_location}/publishers/google/models/{_modelId}";

            var content = new Content
            {
                Role = "user",
                Parts = { new Part { Text = prompt } }
            };

            var generateContentRequest = new GenerateContentRequest
            {
                Model = endpoint,
                Contents = { content }
            };

            var response = await predictionServiceClient.GenerateContentAsync(generateContentRequest);

            if (response.Candidates.Count > 0 && response.Candidates[0].Content?.Parts.Count > 0)
            {
                return response.Candidates[0].Content.Parts[0].Text;
            }

            _logger.LogWarning("No content generated by Gemini AI");
            return string.Empty;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error calling Gemini AI for promotion suggestion");
            
            // Fallback response for development/testing
            return @"{
                ""justificationAI"": ""Based on inventory analysis, combining low-rotation products with high-rotation items can boost sales by creating attractive bundles."",
                ""expectedIncreasePercent"": 15.5,
                ""products"": [
                    {
                        ""productId"": ""PROD001"",
                        ""role"": ""primary"",
                        ""discountPercent"": 20
                    },
                    {
                        ""productId"": ""PROD002"",
                        ""role"": ""combo"",
                        ""discountPercent"": 15
                    }
                ]
            }";
        }
    }

    public async Task<string> AnalyzeInventoryAsync(string data)
    {
        try
        {
            var predictionServiceClient = await PredictionServiceClient.CreateAsync();
            
            var endpoint = $"projects/{_projectId}/locations/{_location}/publishers/google/models/{_modelId}";

            var prompt = $@"Analyze the following inventory data and suggest replenishment needs:
{data}

Provide analysis in JSON format with fields: productId, suggestedQuantity, justification, urgency.";

            var content = new Content
            {
                Role = "user",
                Parts = { new Part { Text = prompt } }
            };

            var generateContentRequest = new GenerateContentRequest
            {
                Model = endpoint,
                Contents = { content }
            };

            var response = await predictionServiceClient.GenerateContentAsync(generateContentRequest);

            if (response.Candidates.Count > 0 && response.Candidates[0].Content?.Parts.Count > 0)
            {
                return response.Candidates[0].Content.Parts[0].Text;
            }

            _logger.LogWarning("No content generated by Gemini AI for inventory analysis");
            return string.Empty;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error calling Gemini AI for inventory analysis");
            
            // Fallback response for development/testing
            return @"{
                ""items"": [
                    {
                        ""productId"": ""PROD003"",
                        ""suggestedQuantity"": 50,
                        ""justification"": ""Stock level below reorder point. Historical data shows consistent demand."",
                        ""urgency"": ""high""
                    }
                ]
            }";
        }
    }
}

