namespace CabriThonAPI.Domain.Entities;

/// <summary>
/// Represents a replenishment order suggestion generated by the AI agent
/// </summary>
public class OrderSuggestion : BaseEntity
{
    public Guid SuggestedOrderId { get; set; }
    public string ClientId { get; set; } = string.Empty;
    public SuggestionStatus Status { get; set; } = SuggestionStatus.Draft;
    public List<OrderItem> Items { get; set; } = new();
    public string? AppliedBy { get; set; }
    public DateTime? AppliedAt { get; set; }
    public decimal TotalEstimatedCost { get; set; }
}

/// <summary>
/// Represents an item within an order suggestion
/// </summary>
public class OrderItem
{
    public Guid Id { get; set; }
    public Guid SuggestedOrderId { get; set; }
    public string ProductId { get; set; } = string.Empty;
    public string ProductName { get; set; } = string.Empty;
    public int SuggestedQuantity { get; set; }
    public string Justification { get; set; } = string.Empty;
    public decimal UnitCost { get; set; }
    public int CurrentStock { get; set; }
    public int ReorderPoint { get; set; }
}

