namespace CabriThonAPI.Domain.Entities;

/// <summary>
/// Represents a promotion suggestion generated by the AI agent
/// </summary>
public class PromotionSuggestion : BaseEntity
{
    public Guid PromotionId { get; set; }
    public string ClientId { get; set; } = string.Empty;
    public string JustificationAI { get; set; } = string.Empty;
    public decimal ExpectedIncreasePercent { get; set; }
    public SuggestionStatus Status { get; set; } = SuggestionStatus.Draft;
    public List<PromotionProduct> Products { get; set; } = new();
    public string? AppliedBy { get; set; }
    public DateTime? AppliedAt { get; set; }
}

/// <summary>
/// Represents a product within a promotion suggestion
/// </summary>
public class PromotionProduct
{
    public Guid Id { get; set; }
    public Guid PromotionId { get; set; }
    public string ProductId { get; set; } = string.Empty;
    public string ProductName { get; set; } = string.Empty;
    public decimal DiscountPercent { get; set; }
    public string Role { get; set; } = string.Empty; // "primary" or "combo"
}

/// <summary>
/// Status of a suggestion
/// </summary>
public enum SuggestionStatus
{
    Draft = 0,
    Approved = 1,
    Rejected = 2,
    Applied = 3
}

